// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/osiloke/gostore_raft/service/proto/service/service.proto

/*
Package gostore_raft_service is a generated protocol buffer package.

It is generated from these files:
	github.com/osiloke/gostore_raft/service/proto/service/service.proto

It has these top-level messages:
	Request
	Response
*/
package gostore_raft_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	ApiAddr  string `protobuf:"bytes,1,opt,name=apiAddr" json:"apiAddr,omitempty"`
	RaftAddr string `protobuf:"bytes,2,opt,name=raftAddr" json:"raftAddr,omitempty"`
	NodeID   string `protobuf:"bytes,3,opt,name=nodeID" json:"nodeID,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetApiAddr() string {
	if m != nil {
		return m.ApiAddr
	}
	return ""
}

func (m *Request) GetRaftAddr() string {
	if m != nil {
		return m.RaftAddr
	}
	return ""
}

func (m *Request) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "gostore_raft.service.Request")
	proto.RegisterType((*Response)(nil), "gostore_raft.service.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Service service

type ServiceClient interface {
	Join(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type serviceClient struct {
	c           client.Client
	serviceName string
}

func NewServiceClient(serviceName string, c client.Client) ServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "gostore_raft.service"
	}
	return &serviceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *serviceClient) Join(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Service.Join", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceHandler interface {
	Join(context.Context, *Request, *Response) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Service{hdlr}, opts...))
}

type Service struct {
	ServiceHandler
}

func (h *Service) Join(ctx context.Context, in *Request, out *Response) error {
	return h.ServiceHandler.Join(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/osiloke/gostore_raft/service/proto/service/service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x2f, 0xce, 0xcc, 0xc9, 0xcf, 0x4e, 0xd5, 0x4f,
	0xcf, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x8d, 0x2f, 0x4a, 0x4c, 0x2b, 0xd1, 0x2f, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0xf3, 0xa0, 0xb4, 0x1e, 0x58, 0x54,
	0x48, 0x04, 0x59, 0x87, 0x1e, 0x54, 0x4e, 0x29, 0x9c, 0x8b, 0x3d, 0x28, 0xb5, 0xb0, 0x34, 0xb5,
	0xb8, 0x44, 0x48, 0x82, 0x8b, 0x3d, 0xb1, 0x20, 0xd3, 0x31, 0x25, 0xa5, 0x48, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x33, 0x08, 0xc6, 0x15, 0x92, 0xe2, 0xe2, 0x00, 0x69, 0x02, 0x4b, 0x31, 0x81, 0xa5,
	0xe0, 0x7c, 0x21, 0x31, 0x2e, 0xb6, 0xbc, 0xfc, 0x94, 0x54, 0x4f, 0x17, 0x09, 0x66, 0xb0, 0x0c,
	0x94, 0xa7, 0x24, 0xc3, 0xc5, 0x11, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc0,
	0xc5, 0x9c, 0x5b, 0x9c, 0x0e, 0x35, 0x15, 0xc4, 0x34, 0x0a, 0xe2, 0x62, 0x0f, 0x86, 0xb8, 0x40,
	0xc8, 0x9d, 0x8b, 0xc5, 0x2b, 0x3f, 0x33, 0x4f, 0x48, 0x56, 0x0f, 0x9b, 0x03, 0xf5, 0xa0, 0xae,
	0x93, 0x92, 0xc3, 0x25, 0x0d, 0xb1, 0x43, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x4f, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x57, 0xe1, 0x5a, 0x22, 0x2e, 0x01, 0x00, 0x00,
}
